[package]
name = "tauri-plugin-o19-ffi"
description = "The Tauri bindings (and foundframe implementation FFI) for o19 Circulari.ty apps."
version = "0.1.0"
edition = "2024"
authors = ["Circulari.ty"]

links = "tauri-plugin-o19-ffi"

[dependencies]
tauri = { version = "2" }
o19-foundframeimpl = { path = "../foundframeimpl" }
thiserror = "2"
reqwest = { version = "0.13.2", features = ["json", "stream"] }
libcaesium = { version = "0.17", features = ["jpg", "webp"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
jni = "0.21.1"
rustls-platform-verifier = "0.6.2"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
tauri-build = "2"
