[package]
name = "o19-foundframeimpl"
description = "The core of a foundational framework (o19) for Circulari.ty apps."
version = "0.1.0"
edition = "2024"
authors = ["Circulari.ty"]
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]

[lib]
crate-type = ["dylib", "rlib"]
bench = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.13.2", features = ["json", "stream"] }
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio-rustls"] }

# for media scraping and previewing
scraper = "0.22"
nom-exif = "2.4"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp", "gif"] }
base64 = "0.22"
blake3 = "1.5"
uuid = { version = "1.10", features = ["v4"] }
